# Generated by Django 4.1.4 on 2023-01-08 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useractivity', '0002_user_confirm_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default=1, max_length=254, unique=True),
        ),
    ]
