# Generated by Django 4.1.4 on 2023-01-09 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useractivity', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='User_id',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
